### ISSUE TITLE
bug: Unauthorized (401) for docker.bintray.io

### ISSUE THREAD

**Issue by mfriedenhagen** [ivanilves/lstags#167]
I checked this with the downloaded binaries v1.0.70 on macOS 10.13.6 (Docker 18.06.0) as well as inside a running `docker:dind` instance, image was just pulled freshly.

When I try to use `lstags`with docker.bintray.io, I seem to be forced to "log in".
```
$ lstags docker.bintray.io/jfrog/artifactory-oss:6.1.0                                                                                                    docker-sync[use-proxy]-
INFO[0000] BATCH 1 of 1                                 
INFO[0000] ANALYZE docker.bintray.io/jfrog/artifactory-oss:6.1.0 
[AUTH::BASIC] Bad response status: 401 Unauthorized >> https://docker.bintray.io/v2
```

However just doing a `docker pull` works without login:
```
$ docker pull docker.bintray.io/jfrog/artifactory-oss:6.1.0                                                                                               docker-sync[use-proxy]-
6.1.0: Pulling from jfrog/artifactory-oss
06b22ddb1913: Pull complete 
336c28b408ed: Pull complete 
1f3e6b8d80c3: Pull complete 
5ccc640979f6: Pull complete 
14eaa20184e6: Pull complete 
19a8522e2399: Pull complete 
39ba9d7befca: Pull complete 
1f81f3143db2: Pull complete 
2034c15120cd: Pull complete 
beafb778b455: Pull complete 
ab88471e705a: Pull complete 
53578522e900: Pull complete 
760817285e89: Pull complete 
69cccd02963b: Pull complete 
47c641ad4383: Pull complete 
805a2133ceca: Pull complete 
ceff12090798: Pull complete 
a01bc8ce0652: Pull complete 
098731d19e70: Pull complete 
Digest: sha256:95eab40f532a0a36bb09755742033dd8abf53172d1d61efcff7178fa247460e5
Status: Downloaded newer image for docker.bintray.io/jfrog/artifactory-oss:6.1.0
```

**Comment by ivanilves** [comment]
hey @mfriedenhagen please try new release: https://github.com/ivanilves/lstags/releases/tag/v1.0.71

it should work now!

**Comment by mfriedenhagen** [comment]
Hello @ivanilves, I built `lstags` from d3eb4b91140c0cea0deca719393ffdbc60a681b3 and was able to use for pulling from docker.bintray.io, thanks a lot for the quick reaction.

Only "nuissance" is the println statement which still shows `[AUTH::BASIC] Bad response status: 401 Unauthorized >> https://docker.bintray.io/v2`, maybe this should go to some kind of debug level, i.e. only appear when run with the verbose switch?

**Comment by vonrabbe** [comment]
This looks solved! Closing. Please re-open if needed.
